language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"
after_success:
  - npm run coveralls
services:
  - postgresql
before_script:
  - psql -c 'create database fast_food_fast_test;' -U postgres
# script:
#   - npm run check-coverage
